### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by vidorgyozo** [pappgergely/Progmatic-201704#2]
I have no tissue.

**Comment by vidorgyozo** [comment]
@pappgergely

**Comment by vidorgyozo** [comment]
- [ ] Hogy

- [ ] kell

- [ ] ezeket

- [ ] kitölteni?

**Comment by vidorgyozo** [comment]
Duplicate issue #1

**Comment by pappgergely** [comment]
`<body>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam, at.</p>
</body>`

**Comment by pappgergely** [comment]
`Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam, at.`

**Comment by vidorgyozo** [comment]
# Header1
## Header2
### Header3
